import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import "./prose-mirror.css";
import { Amplify } from "aws-amplify";
import amplifyconfig from "../../amplify_outputs.json";
import AuthClient from "@/components/authentication/Authentication";
import { TooltipProvider } from "@/components/ui/tooltip";
import { Toaster } from "sonner";
import { CircleCheckIcon, OctagonXIcon } from "lucide-react";
Amplify.configure(amplifyconfig, { ssr: true });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable}  antialiased`}>
        <AuthClient>
          <TooltipProvider>
            <Toaster
              position="top-right"
              icons={{
                success: <CircleCheckIcon className="size-4" />,
                error: <OctagonXIcon className="size-4" />,
              }}
              
              toastOptions={{style: {background: "var(--background)", color: "var(--foreground)"}}}
            />
            {children}
          </TooltipProvider>
        </AuthClient>
      </body>
    </html>
  );
}
